### PR TITLE
fixed caret positioning in wrapped lines (issue #423)

### LINKED ISSUE #423: Wrong character insertion index on multi-line paragraphs when caret positioned at end of line-wrap
````
Line 1 text|
^Line 2 text
*Line 3 text
````
In a multi-line paragraph of at least 3 lines (above diagram), where `|` represents the initial caret position, it is expected that pressing `DOWN` arrow key will move caret to `^`, but it actually moves it to `*`. 

Additionally, pressing `UP` arrow key will not move the caret at all. Once one presses `LEFT` or `RIGHT` arrow key (i.e. press left, then right to reposition the caret at `*`), `UP` works again.

Run the code to reproduce the bug.
````java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.fxmisc.flowless.VirtualizedScrollPane;
import org.fxmisc.richtext.InlineCssTextArea;

public class DownLinesBug extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        String _3LinesOfText = "Some long amount of text to take up a lot of space in the given area.";
        InlineCssTextArea area = new InlineCssTextArea(_3LinesOfText + "\n" + _3LinesOfText);
        area.setWrapText(true);
        VirtualizedScrollPane<InlineCssTextArea> vsPane = new VirtualizedScrollPane<>(area);

        area.moveTo(0, 27);

        Scene scene = new Scene(vsPane, 200, 400);
        primaryStage.setScene(scene);
        primaryStage.show();

        // press [DOWN] Key arrow to reproduce bug
    }
}

````

### PR DESCRIPTION
**Pull request by JFormDesigner**
This PR fixes some issues with caret positioning in **wrapped lines**:

1) pressing `DOWN` key at end of line now moves caret to end of next line (and not beginning of line after next line).
E.g. if caret is at `|` then `DOWN` key moves it to `^` (and not `*` as before).
~~~
01234|
678^
*01
~~~

2) `UP` key now always works as expected (and no longer "locks" at `*` as before)

3) when clicking with the mouse after text in a wrapped line (e.g. right to `^`), then the caret is now positioned at the end of the hit line (and not at the beginning of the next line as before)

Here is some code to reproduce:
~~~java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.fxmisc.flowless.VirtualizedScrollPane;
import org.fxmisc.richtext.InlineCssTextArea;

public class HitWrappedBug extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        InlineCssTextArea area = new InlineCssTextArea("01234 678 01");
        area.setWrapText(true);
        area.setStyle("-fx-font-size: 30pt");
        VirtualizedScrollPane<InlineCssTextArea> vsPane = new VirtualizedScrollPane<>(area);

        Scene scene = new Scene(vsPane, 50, 400);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
~~~

I think this fixes #423

### CODE REVIEW

File: richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java [hunk 1]
```diff
@@ -141,23 +141,36 @@ CharacterHit hitLine(double x, int lineIndex) {
...
+        boolean leading = hit.isLeading();
 
         int lineIdx = getLineIndex((float) y);
         if(lineIdx >= getLineCount()) {
             return CharacterHit.insertionAt(getCharCount());
         }
 
-        TextLine line = getLines()[lineIdx];
+        TextLine[] lines = getLines();
+        TextLine line = lines[lineIdx];
```
Comment (JordanMartinez) [inline richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java]: Did you break this up so that it's easier to read? Or is this "noise" (as some might call it) unintentional?

**Comment by JordanMartinez** [comment]
I'll submit a PR to your repo with a test that can tell us for sure.

**Comment by JordanMartinez** [comment]
@JFormDesigner In your PR, could you add `MultilineJaggerdTests` (see below) into `NavigationTests` by following the example below?
````java
@RunWith(NestedRunner.class)
public class NavigationTests {

// other test classes

// start
    public class MultilineJaggerdTest extends InlineCssTextAreaAppTest {

        String threeLinesOfText = "Some long amount of text to take up a lot of space in the given area.";

        @Override
        public void start(Stage stage) throws Exception {
            super.start(stage);
            stage.setWidth(200);
            area.replaceText(threeLinesOfText);
            area.setWrapText(true);
        }

        private void waitForMultiLineRegistration() throws TimeoutException {
            // When the stage's width changes, TextFlow does not properly handle API calls to a
            //  multi-line paragraph immediately. So, wait until it correctly responds
            //  to the stage width change
            Future<Void> textFlowIsReady = WaitForAsyncUtils.asyncFx(() -> {
                while (area.getParagraphLinesCount(0) != 3) {
                    sleep(10);
                }
            });
            WaitForAsyncUtils.waitFor(5, TimeUnit.SECONDS, textFlowIsReady);
        }

        @Test
        public void pressingDownMovesCaretToNextLine() throws TimeoutException {
            waitForMultiLineRegistration();

            area.moveTo(27);

            push(DOWN);

            assertEquals(57, area.getCaretPosition());
        }

        @Test
        public void pressingUpMovesCaretToPrevLine() throws TimeoutException {
            waitForMultiLineRegistration();

            area.moveTo(66);

            push(UP);

            assertEquals(36, area.getCaretPosition());
        }
    }

// End
}
````

**Comment by JordanMartinez** [comment]
Also, thank you for figuring out a way to resolve this. I'd tried a number of times and never got anything to work since I didn't understand the internal API for TextLayout.

File: richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java (hunk 1 above)
Comment (JFormDesigner) [reply richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java]: No. The `lines` variable is used in a if statement to check whether this is a wrapped paragraph 😉

Comment (JordanMartinez) [reply richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java]: Ah... I see now. Sorry, I misread it.
